spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 9080

  health:
    enabled: true